name: Aspire Cosmos DB Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use the appropriate version

    # Install required dependencies for Cosmos DB Emulator on Linux
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind8 libcurl4 openssl

    # Restore dependencies for both projects
    - name: Restore dependencies
      run: |
        dotnet restore AspireCosmosSimple/AspireCosmosSimple/AspireCosmosSimple.csproj
        dotnet restore AspireCosmosSimple/CosmosDBTest/CosmosDBTest.csproj
    
    # Build both projects
    - name: Build
      run: |
        dotnet build AspireCosmosSimple/AspireCosmosSimple/AspireCosmosSimple.csproj --no-restore
        dotnet build AspireCosmosSimple/CosmosDBTest/CosmosDBTest.csproj --no-restore
    
    # Run Aspire application in background
    - name: Start Aspire with Cosmos DB Emulator
      run: |
        # Create a temporary script to handle non-interactive console
        cat > run_aspire.sh << 'EOF'
        #!/bin/bash
        # Set ASPNETCORE_ENVIRONMENT to Development to ensure proper emulator setup
        export ASPNETCORE_ENVIRONMENT=Development
        
        # Run in background and redirect both stdin and stdout
        dotnet run --project AspireCosmosSimple/AspireCosmosSimple/AspireCosmosSimple.csproj > aspire_output.log 2>&1 &
        ASPIRE_PID=$!
        
        # Verify the process is running
        if ! ps -p $ASPIRE_PID > /dev/null; then
          echo "Failed to start Aspire application"
          exit 1
        fi
        
        echo "Aspire application started with PID: $ASPIRE_PID"
        echo "Waiting for Cosmos DB emulator to initialize..."
        
        # Wait for the application to start and initialize the emulator (longer wait time)
        sleep 120
        
        # Check if the application is still running
        if ! ps -p $ASPIRE_PID > /dev/null; then
          echo "Aspire application terminated unexpectedly"
          cat aspire_output.log
          exit 1
        fi
        
        # Show the latest log entries
        echo "Last 20 lines of Aspire log:"
        tail -n 20 aspire_output.log
        
        # Run the test application
        echo "Running test application to verify Cosmos DB emulator..."
        dotnet run --project AspireCosmosSimple/CosmosDBTest/CosmosDBTest.csproj
        TEST_RESULT=$?
        
        # Kill the Aspire application and clean up
        if ps -p $ASPIRE_PID > /dev/null; then
          echo "Stopping Aspire application..."
          kill $ASPIRE_PID
          wait $ASPIRE_PID 2>/dev/null || true
        fi
        
        # Return the test result
        echo "Test completed with result: $TEST_RESULT"
        exit $TEST_RESULT
        EOF
        
        # Make the script executable
        chmod +x run_aspire.sh
        
        # Run the script
        ./run_aspire.sh
